Move esm samples to jsapi-resources
Esri/feedback-js-api-next pull request #89
Opened 2020-12-07 23:31 UTC by andygup

Pending the 4.18 production release, this PR:
* Updates README
* Updates ESM issue template
* Removes ESM overview page
* Removes ESM samples (in preparation to move them over to jsapi-resources repo)

2020-12-07 23:34 UTC, andygup commented
FYI @odoe (couldn't find you under Reviewers)

2020-12-08 18:28 UTC, dasa requested changes

2020-12-08 18:28 UTC, dasa commented on .github/ISSUE_TEMPLATE/esm.md
> + - Version: [Run `npm ls @arcgis/core` in a terminal window]
Should this be updated for both the CDN or either NPM package?

2020-12-08 18:30 UTC, dasa approved these changes

2020-12-08 18:31 UTC, dasa commented on .github/ISSUE_TEMPLATE/esm.md
> + - Version: [Run `npm ls @arcgis/core` in a terminal window]
Sorry, I see now that this file is specific for the `@arcgis/core` package.

2020-12-08 19:16 UTC, odoe reviewed
I just had the one question for clarification, rest looks good.

2020-12-08 19:16 UTC, odoe commented on .github/ISSUE_TEMPLATE/esm.md
> + - Angular, React, node.js, vue, webpack, rollup [e.g. Angular 10.0.2]
Missing `,` or does this mean Angular `10.0.2` uses rollup?

2020-12-08 19:28 UTC, bsvensson commented
@andygup  We have a fair amount of traffic going to the ESM page, should we maybe leave a stripped down ESM overview page - with some info about (a) it has been released and (b) where to go to for the samples?

2020-12-08 19:30 UTC, andygup commented
@bsvensson I wondered about that, as well. I'll add it back with some verbiage.

2020-12-08 20:31 UTC, andygup commented
@bsvensson fyi, updated ES modules overview page text: https://github.com/Esri/feedback-js-api-next/pull/89/commits/962cb8ad6e55560105c725d2a67214f98129d991

2020-12-17 19:46 UTC, merged